# Generated by Django 5.0 on 2024-01-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Competence name')),
                ('description', models.TextField(verbose_name='About competence')),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
