# Generated by Django 5.0 on 2024-01-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_projet_delete_recentwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(default='default.png', upload_to='clients'),
        ),
    ]
